//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IvanHotel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBReservasiHotelEntities : DbContext
    {
        public DBReservasiHotelEntities()
            : base("name=DBReservasiHotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Alamat> Alamat { get; set; }
        public virtual DbSet<Laundry> Laundry { get; set; }
        public virtual DbSet<Layanan> Layanan { get; set; }
        public virtual DbSet<Pegawai> Pegawai { get; set; }
        public virtual DbSet<Spa> Spa { get; set; }
        public virtual DbSet<Tamu> Tamu { get; set; }
        public virtual DbSet<Fasilitas> Fasilitas { get; set; }
        public virtual DbSet<JenisKelamin> JenisKelamin { get; set; }
        public virtual DbSet<KabupatenKota> KabupatenKota { get; set; }
        public virtual DbSet<Kecamatan> Kecamatan { get; set; }
        public virtual DbSet<Kontak> Kontak { get; set; }
        public virtual DbSet<Provinsi> Provinsi { get; set; }
        public virtual DbSet<TipeIdentitas> TipeIdentitas { get; set; }
        public virtual DbSet<TipeKamar> TipeKamar { get; set; }
        public virtual DbSet<TipeKontak> TipeKontak { get; set; }
        public virtual DbSet<TipeLayanan> TipeLayanan { get; set; }
        public virtual DbSet<TransaksiKamar> TransaksiKamar { get; set; }
        public virtual DbSet<TransaksiLayanan> TransaksiLayanan { get; set; }
        public virtual DbSet<TransaksiTamu> TransaksiTamu { get; set; }
        public virtual DbSet<FasilitasKamar> FasilitasKamar { get; set; }
        public virtual DbSet<Kamar> Kamar { get; set; }
    }
}
