//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IvanHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kamar
    {
        public Kamar()
        {
            this.FasilitasKamar = new HashSet<FasilitasKamar>();
            this.TransaksiKamar = new HashSet<TransaksiKamar>();
        }
    
        public int ID { get; set; }
        public Nullable<int> NomorKamar { get; set; }
        public Nullable<int> Kapasitas { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> TipeKamarID { get; set; }
        public Nullable<int> Lantai { get; set; }
        public Nullable<int> HargaWeekDay { get; set; }
        public Nullable<int> HargaWeekEnd { get; set; }
    
        public virtual ICollection<FasilitasKamar> FasilitasKamar { get; set; }
        public virtual TipeKamar TipeKamar { get; set; }
        public virtual ICollection<TransaksiKamar> TransaksiKamar { get; set; }
    }
}
