//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IvanHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontak
    {
        public int ID { get; set; }
        public Nullable<int> Kontak1 { get; set; }
        public Nullable<int> TipeKontakID { get; set; }
        public Nullable<int> TamuID { get; set; }
    
        public virtual Tamu Tamu { get; set; }
        public virtual TipeKontak TipeKontak { get; set; }
    }
}
