//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IvanHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pegawai
    {
        public Pegawai()
        {
            this.TransaksiTamu = new HashSet<TransaksiTamu>();
        }
    
        public int ID { get; set; }
        public string NIP { get; set; }
        public Nullable<int> Nama { get; set; }
        public Nullable<int> Alamat { get; set; }
    
        public virtual ICollection<TransaksiTamu> TransaksiTamu { get; set; }
    }
}
