//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IvanHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tamu
    {
        public Tamu()
        {
            this.Alamat = new HashSet<Alamat>();
            this.Kontak = new HashSet<Kontak>();
            this.TransaksiTamu = new HashSet<TransaksiTamu>();
        }
    
        public int ID { get; set; }
        public string Nama { get; set; }
        public Nullable<int> NomorIdentitas { get; set; }
        public Nullable<int> TipeIdentitasID { get; set; }
        public Nullable<int> JenisKelaminID { get; set; }
    
        public virtual ICollection<Alamat> Alamat { get; set; }
        public virtual ICollection<Kontak> Kontak { get; set; }
        public virtual JenisKelamin JenisKelamin { get; set; }
        public virtual TipeIdentitas TipeIdentitas { get; set; }
        public virtual ICollection<TransaksiTamu> TransaksiTamu { get; set; }
    }
}
