//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IvanHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransaksiLayanan
    {
        public int ID { get; set; }
        public Nullable<int> LayananID { get; set; }
        public Nullable<int> TransaksiTamuID { get; set; }
    
        public virtual Layanan Layanan { get; set; }
        public virtual TransaksiTamu TransaksiTamu { get; set; }
    }
}
