//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMovie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alamat
    {
        public int ID { get; set; }
        public string Alamat1 { get; set; }
        public Nullable<int> RT { get; set; }
        public Nullable<int> RW { get; set; }
        public Nullable<int> KodePos { get; set; }
        public Nullable<int> KecamatanID { get; set; }
        public Nullable<int> KelurahanID { get; set; }
        public Nullable<int> KabupatenKotaID { get; set; }
        public Nullable<int> TamuID { get; set; }
    
        public virtual KabupatenKota KabupatenKota { get; set; }
        public virtual Kecamatan Kecamatan { get; set; }
        public virtual Tamu Tamu { get; set; }
    }
}
