//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMovie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FasilitasKamar
    {
        public int ID { get; set; }
        public Nullable<int> KamarID { get; set; }
        public Nullable<int> FasilitasID { get; set; }
        public Nullable<int> HargaWeekDay { get; set; }
        public Nullable<int> HargaWeekEnd { get; set; }
    
        public virtual Fasilitas Fasilitas { get; set; }
        public virtual Kamar Kamar { get; set; }
    }
}
