//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMovie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransaksiTamu
    {
        public TransaksiTamu()
        {
            this.TransaksiLayanan = new HashSet<TransaksiLayanan>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> CheckIn { get; set; }
        public Nullable<System.DateTime> CheckOut { get; set; }
        public Nullable<int> TamuID { get; set; }
        public Nullable<int> PegawaiID { get; set; }
        public Nullable<int> KamarID { get; set; }
    
        public virtual ICollection<TransaksiLayanan> TransaksiLayanan { get; set; }
        public virtual Kamar Kamar { get; set; }
        public virtual Pegawai Pegawai { get; set; }
        public virtual Tamu Tamu { get; set; }
    }
}
